In [ ]:
# Here's my notebook for hydrangea location, color, approximate pH, and whether each hydrangea was potted or not.
# I used geojson to plot the lat/long, which I approximated based on google maps screenshots as I was walking and recording + taking photos of hydrangeas.
# Then I downloaded as .csv from geojson and brought this into jupyter notebooks

import pandas as pd
df = pd.read_csv('hydrangeapoints.csv')

In [ ]:
# taking a look at my hydrangea pH data
df

     Color   pH Potted        lon        lat
0     Pink  6.8     No -73.954136  40.674692
1   Purple  5.5     No -73.954204  40.674781
2     Blue  4.5     No -73.955403  40.674948
3     Pink  6.5     No -73.955365  40.674946
4     Blue  4.5     No -73.955470  40.674770
5     Pink  7.0    Yes -73.955570  40.674983
6     Blue  5.0     No -73.961649  40.676321
7     Pink  6.5     No -73.966194  40.676865
8     Pink  7.0    Yes -73.966610  40.677285
9   Purple  5.5     No -73.968090  40.677426
10    Blue  5.0     No -73.967966  40.677398
11  Purple  6.0     No -73.967763  40.677364
12    Blue  4.5     No -73.967096  40.677223
13    Blue  5.0     No -73.966433  40.677098
14    Blue  5.0     No -73.969380  40.677884
15    Blue  4.5     No -73.970756  40.678180
16    Blue  5.0     No -73.971308  40.678312
17    Blue  5.0     No -73.969814  40.677737
18  Purple  5.5     No -73.976778  40.680016
19    Blue  4.5     No -73.976421  40.679671
20  Purple  5.0     No -73.976280  40.679605
21    Pink  6.5    Yes -73.971081  40.678306

In [ ]:
# taking the overall mean pH

df['pH'].mean()

5.468181818181818

In [ ]:
# taking the mean pH of potted/unpotted hydrangeas
df.groupby('Potted')['pH'].mean()

Potted
No     5.252632
Yes    6.833333
Name: pH, dtype: float64

In [ ]:
# taking the median pH of potted/unpotted hydrangeas, to compare

df.groupby('Potted')['pH'].median()

Potted
No     5.0
Yes    7.0
Name: pH, dtype: float64